package com.pocketpenguin;

/** Generated by tools/make_buddy_assets.py. Offsets of each cropped PNG inside the 800x520 design canvas (ground y = 500). */
final class BuddyLayout {
    static final int CANVAS_W = 800, CANVAS_H = 520;
    static final int BD_BODY_L = 49, BD_BODY_T = 123;
    static final int BD_FIN_L = 370, BD_FIN_T = 386;
    static final int BD_TAIL_L = 3, BD_TAIL_T = 172;
}
