package com.pocketpenguin;

/** Generated by tools/make_assets.py. Offsets of each cropped PNG inside the 640x800 design canvas. */
final class PartLayout {
    static final int CANVAS_W = 640, CANVAS_H = 800;
    static final int PG_BODY_L = 106, PG_BODY_T = 355;
    static final int PG_HEAD_L = 76, PG_HEAD_T = 43;
    static final int PG_BEAK_L = 258, PG_BEAK_T = 323;
    static final int PG_WING_L_L = 40, PG_WING_L_T = 400;
    static final int PG_WING_R_L = 407, PG_WING_R_T = 400;
    static final int PG_FOOT_L_L = 177, PG_FOOT_L_T = 694;
    static final int PG_FOOT_R_L = 325, PG_FOOT_R_T = 694;
    static final int PG_TAIL_L = 399, PG_TAIL_T = 635;
}
