# Original "Jinbei" (whale-shark plush buddy) part art for Pocket Penguin v0.7 (Pillow; no third-party art used).
# Usage: python3 tools/make_buddy_assets.py [out_dir]  -> bd_body.png, bd_fin.png, bd_tail.png, BuddyLayout.java, _preview.png
import numpy as np, math, os, sys, random
from PIL import Image, ImageDraw
from scipy.ndimage import gaussian_filter, distance_transform_edt

W, H, S = 800, 520, 3
OUT_DIR = sys.argv[1] if len(sys.argv) > 1 else 'out_buddy'
os.makedirs(OUT_DIR, exist_ok=True)
OUTLINE = (16, 17, 20, 255)            # same ink colour as the penguin so both read as one cast
BLUE = (122, 184, 206, 255); BLUE_SH = (98, 158, 186, 255); BLUE_HI = (166, 212, 228, 255)
CREAM = (255, 246, 226, 255); CREAM_SH = (240, 226, 198, 255)
PINK = (255, 208, 212, 255); PINK_SH = (240, 172, 184, 255); PINK_DK = (222, 140, 156, 255)
DOT = (255, 252, 244, 255)

def _draw(pts):
    im = Image.new('L', (W*S, H*S), 0); ImageDraw.Draw(im).polygon([(x*S, y*S) for x, y in pts], fill=255)
    return np.array(im) > 127
def ell(cx, cy, rx, ry, ang=0.0, n=180):
    a = math.radians(ang); pts = []
    for i in range(n):
        t = 2*math.pi*i/n; x, y = rx*math.cos(t), ry*math.sin(t)
        pts.append((cx + x*math.cos(a) - y*math.sin(a), cy + x*math.sin(a) + y*math.cos(a)))
    return _draw(pts)
def smooth(m, r): return gaussian_filter(m.astype(np.float32), r*S) > 0.5
def grow(m, t): return distance_transform_edt(~m) <= t*S
def compose(layers):
    im = Image.new('RGBA', (W*S, H*S), (0, 0, 0, 0))
    for mask, col in layers:
        im.paste(Image.new('RGBA', im.size, col), mask=Image.fromarray((mask*255).astype(np.uint8)))
    return im
layout = {}
def finish(img, name):
    small = img.resize((W, H), Image.LANCZOS); bb = small.getbbox(); pad = 3
    l, t, r, b = max(0, bb[0]-pad), max(0, bb[1]-pad), min(W, bb[2]+pad), min(H, bb[3]+pad)
    small.crop((l, t, r, b)).save(os.path.join(OUT_DIR, name + '.png')); layout[name] = (l, t, r-l, b-t); return small

def dots(region, seed, rmin=11, rmax=21, step=74, exclude=()):
    rnd = random.Random(seed); m = np.zeros((H*S, W*S), bool)
    for row, y in enumerate(range(150, 480, int(step*.86))):
        for x in range(40 + (step//2 if row % 2 else 0), W, step):
            cx, cy = x + rnd.uniform(-10, 10), y + rnd.uniform(-9, 9); r = rnd.uniform(rmin, rmax)
            if any(math.hypot(cx-ex, cy-ey) < er for ex, ey, er in exclude): continue
            m |= ell(cx, cy, r, r*rnd.uniform(.92, 1.0), rnd.uniform(0, 180), 40)
    return m & region

# ---- body: chubby bean, blunt snout on the right, small dorsal bump
body = smooth(ell(380, 338, 292, 156) | ell(575, 346, 178, 148) | ell(190, 340, 120, 112) | ell(300, 196, 44, 54, -16), 8)
blue_zone = smooth(ell(420, 258, 330, 150) | ell(585, 300, 165, 128), 8)
blue = body & blue_zone; cream = body & ~blue_zone
mouth_zone = smooth(ell(712, 416, 84, 90), 4) & body
shade = body & ~ell(400, 238, 340, 128)
sheen = ell(300, 232, 74, 15, -8) & blue
eye_clear = [(584, 338, 54)]
dm = dots(blue, 7, exclude=eye_clear)
layers = [(grow(body, 15), OUTLINE), (body, BLUE), (cream, CREAM), (cream & ~ell(400, 300, 330, 200), CREAM_SH),
          (blue & shade, BLUE_SH), (sheen, BLUE_HI), (dm, DOT), (mouth_zone, PINK), (mouth_zone & ~ell(712, 392, 90, 84), PINK_SH)]
# cream band edge outline-ish seam (thin) between blue and cream: subtle
seam = grow(blue, 2) & ~blue & body
layers.insert(4, (seam, (210, 196, 168, 255)))
img_body = finish(compose(layers), 'bd_body')

# ---- pectoral fin (pivot ~ (505, 432)); drawn in front of the body
fin = smooth(ell(452, 450, 72, 30, 148) | ell(408, 470, 21, 13, 148), 4)
fl = [(grow(fin, 13), OUTLINE), (fin, BLUE), (fin & ~ell(472, 424, 74, 24, 148), BLUE_SH), (dots(fin, 3, 7, 11, 52), DOT), (ell(464, 436, 36, 7, 148) & fin, BLUE_HI)]
finish(compose(fl), 'bd_fin')

# ---- tail (attached at ~ (150, 340)); vertical crescent flukes
stalk = ell(112, 338, 56, 40)
upper = ell(62, 262, 30, 78, 22); lower = ell(66, 404, 24, 52, -22)
tail = smooth(stalk | upper | lower | ell(84, 334, 34, 112), 7)
tl = [(grow(tail, 13), OUTLINE), (tail, BLUE), (tail & ~ell(100, 300, 90, 120), BLUE_SH), (dots(tail, 11, 8, 13, 56), DOT)]
finish(compose(tl), 'bd_tail')

# ---- preview with runtime-style face
cv = Image.new('RGBA', (W, H), (236, 214, 176, 255))
for n in ['bd_tail', 'bd_body', 'bd_fin']:
    im = Image.open(os.path.join(OUT_DIR, n + '.png')); l, t, w, h = layout[n]; cv.alpha_composite(im, (l, t))
d = ImageDraw.Draw(cv)
d.arc([556, 326, 618, 368], 200, 340, fill=OUTLINE, width=7)
d.ellipse([520, 366, 562, 390], fill=(247, 188, 184, 200))
cv.convert('RGB').save(os.path.join(OUT_DIR, '_preview.png'))
with open(os.path.join(OUT_DIR, 'BuddyLayout.java'), 'w') as f:
    f.write('package com.pocketpenguin;\n\n/** Generated by tools/make_buddy_assets.py. Offsets of each cropped PNG inside the 800x520 design canvas (ground y = 500). */\nfinal class BuddyLayout {\n')
    f.write('    static final int CANVAS_W = %d, CANVAS_H = %d;\n' % (W, H))
    for k, (l, t, w, h) in layout.items(): f.write('    static final int %s_L = %d, %s_T = %d;\n' % (k.upper(), l, k.upper(), t))
    f.write('}\n')
print(layout)
